export class ProfileUser {
    constructor(
               public  userImage?:string,
               public jobTitle?: string,
               public educationLevel?: string,
               public age?: number,
               public languages?: any[],
                public experience?: number,
                public coverLetter?: string,
                public phoneNumber?: number,
                public websiteLink?: string,
                public facebookLink?: string,
                public twitterLink?: string,
                public googleLink?: string,
                public linkedinLink?: string,
                public country?: string,
                public city?: string,
                public address?: string,
                public categories?:string,
               public educationTitle?: string,
                public educationFrom?: Date,
                public educationTo?: Date,
                public  educationInstitue?: string,
                public  educationDescription?: string,
              public workTitle?: string,
                public workFrom?: Date,
                public workTo?: Date,
                public  workCompany?: string,
                public  workDescription?: string,
                public name?:string,
                public email?:string,
                public memberSince?:Date,

              ) {}
}
